feat: skeleton contract & user-specific target dir
D3LAB-DAO/cosmonaut-api pull request #1
Opened 2022-07-21 07:56 UTC by demibun

1. make skeleton-init USER_ID=user-id WHICH_LESSON=1 WHICH_CHAPTER=6
2. make run-contract USER_ID=user-id WHICH_LESSON=1 WHICH_CHAPTER=6

2022-07-21 12:37 UTC, tkxkd0159 requested changes

2022-07-21 12:37 UTC, tkxkd0159 commented on cargo-projects/scripts/run.sh
> +fi
- internal_run.sh가 해당 PR에 포함안되어 있네여. 실행같은 경우에는 bash로 workspace root에서 스크립트 안의 서브배쉬로 실행시키는 것보다 각 유저의 각 챕터를 기준으로 root로 잡아서 cargo 명령어로 다이렉트로 실행시킬 수 있으면 좋을 것 같아요.
- 서빙 시 볼륨 세팅이 필요하기 때문에 base volume 만드는 `Dockerfile`도 추가해주세요.

2022-07-21 12:37 UTC, tkxkd0159 commented on cargo-projects/scripts/init_skeleton.sh
> +else
이 부문은 target path로 기반으로 생성되는 기존 백엔드 인터페이스랑 안맞아서 나중에 제가 커스텀해서 사용하겠습니다.

2022-07-22 07:21 UTC, demibun commented on cargo-projects/scripts/run.sh
> +    cosmonaut-contract:1.0.0 cargo run --manifest-path ${USER_CONTRACT_DIR}/Cargo.toml $WHICH_LESSON $WHICH_CHAPTER
compose.rust.Dockerfile 빌드명으로 변경 필요합니다

2022-07-22 07:25 UTC, demibun commented on compose.rust.Dockerfile
> +RUN ln -s /workspace/cargo-projects/cosm-base /usr/local/cargo/registry
cargo registry를 볼륨과 연결하여 index를 재생성 하지 않도록 합니다

2022-07-25 08:17 UTC, merged